default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRESS_USER'] %>
  password: <%= ENV['POSTGRESS_PWD'] %>

development:
  <<: *default
  database: anthill_development

test:
  <<: *default
  database: anthill_test

production:
  <<: *default
  database: anthill_development