mysql: &mysql
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PWD'] %>
  host: 127.0.0.1
  port: 3306

postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRESS_USER'] %>
  password: <%= ENV['POSTGRESS_PWD'] %>

default: &default
  <% unless (ENV['PATH'] =~ /teamco/).nil? %>
    <% if (RUBY_PLATFORM =~ /darwin/).nil? %>
      <<: *mysql
    <% else %>
      <<: *postgresql
    <% end %>
  <% else %>
    <<: *postgresql
  <% end %>  

development:
  <<: *default
  database: anthill_development

test:
  <<: *default
  database: anthill_test

production:
  <<: *default
  database: anthill_development