default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRESS_USER'] %>
  password: <%= ENV['POSTGRESS_PWD'] %>

#  adapter: mysql2
#  pool: 5
#  username: root
#  password: 09051972
#  socket: /tmp/mysql.sock
#  host: 127.0.0.1
#  port: 3306
#  encoding: utf8mb4
#  collation: utf8mb4_bin


development:
  <<: *default
  database: anthill_development

test:
  <<: *default
  database: anthill_test

production:
  <<: *default
  database: anthill_development
#heroku:
#  adapter: postgresql
#  encoding: unicode
#  database: ENV['DATABASE_URL']
#  username: ENV['DATABASE_USERNAME']
#  password: ENV['DATABASE_PASSWORDs']
